# Generated by Django 3.2 on 2021-06-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0003_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_item',
        ),
    ]
