# Generated by Django 3.2 on 2021-06-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0006_auto_20210610_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall_message',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='wall_message',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Wall_Message',
        ),
    ]
