# Generated by Django 3.2 on 2021-06-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0008_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
